version: "3"

services:
  rails:
    image: tamle:lastest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 80:80
    links:
      - db
  db:
    image: postgres:11.10
    environment:
      - POSTGRES_DB=shorten_url_development
      - POSTGRES_USER=stu1
      - POSTGRES_PASSWORD=stu1sEcRet
    ports:
      - 5432:5432