version: "3"

services:
  rails:
    image: tamle:lastest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 80:80
    links:
      - db
  db:
    image: postgres:11.10
    environment:
      - POSTGRES_DB=google_crawler_development
      - POSTGRES_USER=gcu1
      - POSTGRES_PASSWORD=gcu1sEcRet
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data: